name: fastconnect
description: A campus-exclusive social networking app for FAST-NU.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  get_it: ^9.1.1
  equatable: ^2.0.7
  cupertino_icons: ^1.0.6

  # State Management
  provider: ^6.1.2
  flutter_bloc: ^8.1.3

  # Networking
  http: ^1.2.1

  # Storage
  shared_preferences: ^2.3.1
  flutter_secure_storage: ^9.0.0

  # Firebase (fixed versions)
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.17.5

  # Media
  image_picker: ^1.1.1
  video_player: ^2.7.2

  # Routing
  go_router: ^14.1.0

  # Real Time
  web_socket_channel: ^3.0.1

  # JSON
  json_annotation: ^4.8.1
  sqflite: ^2.4.2
  path_provider: ^2.1.1
  path: ^1.9.1
  jwt_decoder: ^2.0.1
  dartz: ^0.10.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
